// <auto-generated />
using System;
using CrewSchedule.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrewSchedule.Infrastructure.Migrations
{
    [DbContext(typeof(CrewDbContext))]
    [Migration("20260225151517_InitialCrew")]
    partial class InitialCrew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrewSchedule.Domain.Aggregates.CrewFlightHours", b =>
                {
                    b.Property<Guid>("CrewMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CrewMemberId");

                    b.ToTable("CrewFlightHours");
                });

            modelBuilder.Entity("CrewSchedule.Domain.Aggregates.SwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromCrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToCrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SwapRequests");
                });

            modelBuilder.Entity("CrewSchedule.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CheckInTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FlightId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FlightId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.HasIndex("FlightId1");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("CrewSchedule.Domain.Entities.CrewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("CrewSchedule.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ArrivalTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DepartureTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("CrewSchedule.Domain.Aggregates.CrewFlightHours", b =>
                {
                    b.OwnsMany("CrewSchedule.Domain.ValueObjects.FlightTimeEntry", "FlightTimeEntries", b1 =>
                        {
                            b1.Property<Guid>("CrewFlightHoursId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("FlightDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Minutes")
                                .HasColumnType("int");

                            b1.HasKey("CrewFlightHoursId", "Id");

                            b1.ToTable("FlightTimeEntry");

                            b1.WithOwner()
                                .HasForeignKey("CrewFlightHoursId");
                        });

                    b.Navigation("FlightTimeEntries");
                });

            modelBuilder.Entity("CrewSchedule.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("CrewSchedule.Domain.Entities.CrewMember", null)
                        .WithMany()
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewSchedule.Domain.Entities.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewSchedule.Domain.Entities.Flight", null)
                        .WithMany("Assignments")
                        .HasForeignKey("FlightId1");
                });

            modelBuilder.Entity("CrewSchedule.Domain.Entities.Flight", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
